name: Build Installer Final

run-name: Final Build

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Build Installer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
        
      - name: Restore Dependencies
        run: dotnet restore
        
      - name: Build for Windows
        run: dotnet publish --no-restore -r win-x64

      - name: Upload Artifact for Windows
        uses: actions/upload-artifact@v4
        with:
          name: MelonLoader.Installer
          path: Output/win-x64/
        
      - name: Build for Linux
        run: dotnet publish --no-restore -r linux-x64

      - name: Upload Artifact for Linux
        uses: actions/upload-artifact@v4
        with:
          name: MelonLoader.Installer.Linux
          path: Output/linux-x64/